apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: billcom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 3; done']
      containers:
        - name: user-service
          image: billcom/user-service:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billcom-secrets
                  key: user-service-database-url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: billcom-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: billcom-config
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: billcom-secrets
                  key: jwt-secret
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: billcom-config
                  key: JWT_ALGORITHM
            - name: PORT
              value: "8001"
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: billcom-config
                  key: PYTHONPATH
          resources:
            requests:
              cpu: "100m"     # 0.1 vCPU garanti — HPA scale up si > 70m (70%)
              memory: "96Mi"
            limits:
              cpu: "300m"     # user-service : moins de trafic que product/order
              memory: "384Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: billcom
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
